name: mysporti
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_datetime_picker: ^1.3.8
  intl: ^0.16.1
  http: ^0.12.1
  shared_preferences: ^0.5.7+2
  provider: ^4.1.0
  flutter_phoenix: ^0.1.0
  flutter_bloc: ^3.0.0
  meta: ^1.1.6
  equatable: ^1.0.0
  webview_flutter: ^0.3.22+1
  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/logo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
